version: '3.4'

services:
  prueba:
    image: ${DOCKER_REGISTRY-}prueba
    container_name: prueba
    restart: always
    build:
      context: .
      dockerfile: prueba/Dockerfile
    ports:
      - "5003:80"
    volumes:
      - ./certs:/etc/docker/certificado:ro
    environment:
      - ASPNETCORE_URLS=https://*:5003
      - DOTNET_SYSTEM_CERTIFICATE_FILE=/etc/docker/certificado.p12
      - DOTNET_SYSTEM_CERTIFICATE_STORE=My
      - DOTNET_SYSTEM_CERTIFICATE_PASSWORD=Ecuador123