name: prueba

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        USER: elsham
        PASS: Ecuador.123
      run: docker login -u "$USER" -p "$PASS"
    - name: Build Images
      run: docker-compose build --no-cache
    - name: Deploy
      run: docker-compose up -d
